	SELECT CODIGO_SICA, '1700100378'
	, ESTADO_FINCA, 'ACT'
	/*
	comentario1
	*/
	, CN_USUARIO_MODIFICACION, 'SICA_USER'
	, FECHA_MODIFICACION, SYSDATE
	--comentario2
	, Fecha_Inactivacion, TO_DATE('31/01/2016', 'dd/mm/yyyy')
	, Area_Cultivo, 6,24
	FROM SICA.SC_FINCA
	WHERE CODIGO_SICA ='2529300114'
	ORDER BY ESTADO_FINCA
	;